[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.26"

[features]
seeds = false
skip-lint = false

[programs.localnet]
megagram = "6YrK9zX5BdiYFpYRm16AA6vaUmFgaUKaEs3Ut7dWzSPX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/megagram.js"